### ISSUE TITLE
Align with resource-metadata-schema requests regarding vpConnection

### ISSUE THREAD

**Issue by henrietteharmse** [ejp-rd-vp/resource-metadata-schema-ontology#1]
See:
[https://github.com/ejp-rd-vp/resource-metadata-schema/issues/45](https://github.com/ejp-rd-vp/resource-metadata-schema/issues/45)
[https://github.com/ejp-rd-vp/resource-metadata-schema/issues/40](https://github.com/ejp-rd-vp/resource-metadata-schema/issues/40)

**Comment by henrietteharmse** [comment]
Changes applied as follows:
![image](https://github.com/ejp-rd-vp/resource-metadata-schema-ontology/assets/32327979/5f5b3834-1ff6-4229-b733-3694334b4817)
![image](https://github.com/ejp-rd-vp/resource-metadata-schema-ontology/assets/32327979/b5108be3-19dd-4c06-9349-f5f77929f2f7)

**Comment by markwilkinson** [comment]
In keeping with the OA decisions, the following term should be deprecated:

    

    <owl:Class rdf:about="http://purl.org/ejp-rd/vocabulary/VPContentDiscovery">
        <rdfs:subClassOf rdf:resource="http://purl.org/ejp-rd/vocabulary/VPConnection"/>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">VPContentDiscovery</rdfs:label>
    </owl:Class>

There will be two new terms:

    <owl:Class rdf:about="http://purl.org/ejp-rd/vocabulary/VPBeacon2_individuals">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">VPBeacon2_individuals</rdfs:label>
    </owl:Class>

    <owl:Class rdf:about="http://purl.org/ejp-rd/vocabulary/VPBeacon2_catalog">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">VPBeacon2_catalog</rdfs:label>
    </owl:Class>

I would also suggest that an appropriate parent class for these two classes would be http://edamontology.org/operation_2421  (Database Search) 

These will be used as annotations for dcat:dataServices using the dct:type  predicate, as recommended in the DCAT2 specification: https://www.w3.org/TR/vocab-dcat-2/#a-dataset-available-from-a-service

**Comment by henrietteharmse** [comment]
@HaddadTala @markwilkinson Can either of you provide descriptions for `VPBeacon2_individuals` and `VPBeacon2_catalog`?
