### ISSUE TITLE
http://purl.obolibrary.org/obo/operation_2421 not resolving, was EDAM intended?

### ISSUE THREAD

**Issue by mroos** [ejp-rd-vp/resource-metadata-schema-ontology#5]
In the metadata model I find
http://purl.obolibrary.org/obo/operation_2421

That does not appear to exist in OBO ontologies. 
Was http://edamontology.org/operation_2421 intended?

If so, I guess that at least 6 Beacon classes will have to be updated, and maybe the 2 other http://purl.obolibrary.org/obo/operation_2421 statements too.

**Comment by markwilkinson** [comment]
done
